name: njajan_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  get_it: ^7.7.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  path: ^1.9.0
  pull_to_refresh: ^2.0.0
  scroll_date_picker: ^3.8.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/sammy/
    - assets/banner/
    - assets/shop/
    - assets/categories/
    - assets/profil/
    - assets/favorite/
    - assets/images/
    - assets/cart/
